apiVersion: apps/v1
kind: Deployment

metadata:

  name: notejam-deployment
  labels:
    app: notejam

spec:

  replicas: 1

  selector:

    matchLabels:

      app: notejam

  template:

    metadata:

      labels:

        app: notejam

    spec:

      containers:

      - name: nodeserver

        image: mohit1301/frontend:latest

        ports:

        - containerPort: 3000



---

 

apiVersion: v1

kind: Service

metadata:

  name: notejam-service

spec:

  selector:

    app: notejam 

  type: LoadBalancer

  ports:

  - protocol: TCP

    port: 5000

    targetPort: 3000

    nodePort: 31110
