apiVersion: v1
kind: Service
metadata:
  name: notejam-service
spec:
  selector:
    app: notejam-app
  ports:
  - name: notejam-app
    protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort   
